<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>PolkitProxy</name>
    <message>
        <location filename="../src/daemon/proxy/polkit-proxy.cpp" line="215"/>
        <source>Authorization failed.</source>
        <translation>Зөвшөөрөл амжилтгүй болсон</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <location filename="../src/daemon/error.cpp" line="30"/>
        <source>Authentication ID already exists.</source>
        <translation>Гэрчлэх ID аль хэдийн байна</translation>
    </message>
    <message>
        <location filename="../src/daemon/error.cpp" line="33"/>
        <source>The user is enrolling.</source>
        <translation>Хэрэглэгч бүртгүүлж байна</translation>
    </message>
    <message>
        <location filename="../src/daemon/error.cpp" line="36"/>
        <source>Too many sessions.</source>
        <translation>Хэт олон яриа</translation>
    </message>
    <message>
        <location filename="../src/daemon/error.cpp" line="39"/>
        <source>The session is in authentication.</source>
        <translation>Сешн нь гэрчлэгдсэн байна</translation>
    </message>
    <message>
        <location filename="../src/daemon/error.cpp" line="42"/>
        <source>Internel error.</source>
        <translation>Дотоод алдаа</translation>
    </message>
    <message>
        <location filename="../src/daemon/error.cpp" line="45"/>
        <source>Unknown error.</source>
        <translation>Үл мэдэгдэх алдаа</translation>
    </message>
    <message>
        <location filename="../src/daemon/error.cpp" line="49"/>
        <source> (error code: 0x%x)</source>
        <translation>Алдааны код 0x%</translation>
    </message>
    <message>
        <location filename="../src/daemon/utils.cpp" line="172"/>
        <source>Enrollment completed successfully.</source>
        <translation>Бүртгэл амжилттай дууссан</translation>
    </message>
    <message>
        <location filename="../src/daemon/utils.cpp" line="174"/>
        <source>Enrollment failed.</source>
        <translation>Бүртгэл амжилтгүй болсон</translation>
    </message>
    <message>
        <location filename="../src/daemon/utils.cpp" line="176"/>
        <source>Enroll stage passed.</source>
        <translation>Бүртгэлийн үе шат өнгөрсөн</translation>
    </message>
    <message>
        <location filename="../src/daemon/utils.cpp" line="179"/>
        <source>The enrollment scan did not succeed, please retry it.</source>
        <translation>Бүртгэлийн скан амжилтгүй болсон тул дахин оролдоно уу</translation>
    </message>
    <message>
        <location filename="../src/daemon/utils.cpp" line="181"/>
        <source>The finger swipe was too short, please retry it.</source>
        <translation>Хуруу хэт богино байна, дахин оролдоно уу</translation>
    </message>
    <message>
        <location filename="../src/daemon/utils.cpp" line="183"/>
        <source>The finger was not centered on the scanner, please retry it.</source>
        <translation>Хуруу нь сканнерын төвд байхгүй байна, дахин оролдоно уу</translation>
    </message>
    <message>
        <location filename="../src/daemon/utils.cpp" line="185"/>
        <source>Unknown enrollment error.</source>
        <translation>Бүртгэлийн алдаа тодорхойгүй байна</translation>
    </message>
    <message>
        <location filename="../src/daemon/utils.cpp" line="195"/>
        <source>Feature not match.</source>
        <translation>Функц таарахгүй байна</translation>
    </message>
    <message>
        <location filename="../src/daemon/utils.cpp" line="197"/>
        <source>Feature matching successed.</source>
        <translation>Онцлог шинж чанар амжилттай таарч байна</translation>
    </message>
    <message>
        <location filename="../src/daemon/utils.cpp" line="199"/>
        <source>Feature not match, please retry it.</source>
        <translation>Функц таарахгүй байна уу, дахин оролдоно уу</translation>
    </message>
    <message>
        <location filename="../src/daemon/utils.cpp" line="202"/>
        <source>Unknown verfication error.</source>
        <translation>Баталгаажуулалтын алдаа тодорхойгүй байна</translation>
    </message>
</context>
</TS>
