<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>Kiran::PolkitProxy</name>
    <message>
        <location filename="../src/daemon/proxy/polkit-proxy.cpp" line="215"/>
        <source>Authorization failed.</source>
        <translation>认证失败。</translation>
    </message>
</context>
<context>
    <name>Kiran::User</name>
    <message>
        <location filename="../src/daemon/user.cpp" line="165"/>
        <source>Enroll has been interrupted. Please wait</source>
        <translation>录入中断请稍等</translation>
    </message>
    <message>
        <location filename="../src/daemon/user.cpp" line="171"/>
        <source>Enroll has been cancelled</source>
        <translation>录入已被取消</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <location filename="../src/daemon/error.cpp" line="30"/>
        <source>Authentication ID already exists.</source>
        <translation>认证ID已存在。</translation>
    </message>
    <message>
        <location filename="../src/daemon/error.cpp" line="33"/>
        <source>The user is enrolling.</source>
        <translation>用户正在录入中。</translation>
    </message>
    <message>
        <location filename="../src/daemon/error.cpp" line="36"/>
        <source>Too many sessions.</source>
        <translation>过多认证会话。</translation>
    </message>
    <message>
        <location filename="../src/daemon/error.cpp" line="39"/>
        <source>The session is in authentication.</source>
        <translation>该会话正在认证中。</translation>
    </message>
    <message>
        <location filename="../src/daemon/error.cpp" line="42"/>
        <source>Internel error.</source>
        <translation>内部错误。</translation>
    </message>
    <message>
        <location filename="../src/daemon/error.cpp" line="45"/>
        <source>No Such Device.</source>
        <translation>不存在该类型设备。</translation>
    </message>
    <message>
        <location filename="../src/daemon/error.cpp" line="48"/>
        <source>Unknown error.</source>
        <translation>未知错误。</translation>
    </message>
    <message>
        <location filename="../src/daemon/error.cpp" line="52"/>
        <source> (error code: 0x%x)</source>
        <translation> (错误码:0x%x)</translation>
    </message>
    <message>
        <location filename="../src/utils/utils.cpp" line="183"/>
        <source>Feature not match.</source>
        <translation>特征不匹配。</translation>
    </message>
    <message>
        <location filename="../src/utils/utils.cpp" line="185"/>
        <source>Feature matching successed.</source>
        <translation>特征匹配成功。</translation>
    </message>
    <message>
        <location filename="../src/utils/utils.cpp" line="187"/>
        <source>Feature not match, please retry it.</source>
        <translation>特征不匹配，请重试。</translation>
    </message>
    <message>
        <location filename="../src/utils/utils.cpp" line="190"/>
        <source>Unknown verfication error.</source>
        <translation>未知认证错误。</translation>
    </message>
</context>
</TS>
